FROM mariadb:latest
RUN apt-get update
RUN apt-get install -y iputils-ping traceroute coreutils net-tools vim nano curl iproute2 openssh-server openssh-client sshpass netcat-openbsd default-mysql-client
# RUN echo "root:PASSWORD" | chpasswd
